// Copyright NineMind, Inc. 2026. All Rights Reserved.
// This file is licensed under the MIT License.
// License text available at https://opensource.org/license/mit/

import {describe, expect, it} from 'vitest';
import {generateWorker} from '../../generate-worker.js';

describe('generateWorker', () => {
  const src = generateWorker({
    entry: '../../../dist/main.js',
    exportName: 'buildApp',
  });
  it('imports the builder and uses the fetch path', () => {
    expect(src).toContain("import {buildApp} from '../../../dist/main.js'");
    expect(src).toContain('fetchHandler()');
    expect(src).not.toContain('expressApp');
    expect(src).not.toContain('@vercel/node');
  });
  it('exports default { fetch } and memoizes the boot', () => {
    expect(src).toContain('export default');
    expect(src).toContain('fetch');
    expect(src).toContain('??=');
    expect(src).toContain('listen: false');
  });
  it('carries the generic generated-by marker', () => {
    expect(src).toContain('Generated by `agentback deploy`');
  });
});
