// Copyright Ninemind.ai 2026. All Rights Reserved.
// This file is licensed under the MIT License.
// License text available at https://opensource.org/license/mit/

export function generateWorker(b: {entry: string; exportName: string}): string {
  return `// Generated by \`agentback deploy\`. Safe to --eject and edit.
// Cloudflare Workers: export a fetch handler built from the runtime-neutral
// RestServer.fetchHandler(). Importing the fetch path (not app.start()) lets
// wrangler's esbuild tree-shake the Node listener out.
import {${b.exportName}} from '${b.entry}';

let booted: Promise<{fetch(req: Request): Promise<Response>}> | undefined;
const host = () =>
  (booted ??= (async () => {
    const app = await ${b.exportName}({listen: false});
    const server = await app.restServer;
    return server.fetchHandler();
  })());

export default {
  async fetch(req: Request): Promise<Response> {
    return (await host()).fetch(req);
  },
};
`;
}
