// Copyright ninemind.ai 2026. All Rights Reserved.
// This file is licensed under the MIT License.
// License text available at https://opensource.org/license/mit/

export function generateWorker(b: {entry: string; exportName: string}): string {
  return `// Generated by \`agentback deploy\`. Safe to --eject and edit.
// Cloudflare Workers: export a fetch handler built from the runtime-neutral
// RestServer.fetchHandler().
//
// The app is built lazily on the FIRST REQUEST, not at module scope: Workers
// forbid IO and randomness (the DI container generates ids) during global
// evaluation, so a module-scope build throws at startup.
//
// REQUIRED: your builder (\`${b.exportName}\`) must construct the app with
// \`rest: {listener: 'native'}\`. In the default 'express' listener, app.start()
// mounts routes on Express, which loads the Node-only \`express\` runtime via
// createRequire(import.meta.url) and throws on a Worker isolate.
import {${b.exportName}} from '${b.entry}';

let booted: Promise<{fetch(req: Request): Promise<Response>}> | undefined;
const host = () =>
  (booted ??= (async () => {
    const app = await ${b.exportName}({listen: false});
    const server = await app.restServer;
    return server.fetchHandler();
  })());

export default {
  async fetch(req: Request): Promise<Response> {
    return (await host()).fetch(req);
  },
};
`;
}
