// Copyright ninemind.ai 2026. All Rights Reserved.
// This file is licensed under the MIT License.
// License text available at https://opensource.org/license/mit/

export function generateEntry(b: {entry: string; exportName: string}): string {
  return `// Generated by \`agentback deploy\`. Safe to --eject and edit.
// Vercel owns the listener: boot with listen:false and hand it the Express app.
import type {IncomingMessage, ServerResponse} from 'node:http';
import {${b.exportName}} from '${b.entry}';

type NodeHandler = (req: IncomingMessage, res: ServerResponse) => void;

let booted: Promise<NodeHandler> | undefined;
const app = (): Promise<NodeHandler> =>
  (booted ??= (async () => {
    const a = await ${b.exportName}({listen: false});
    const server = await a.restServer;
    return server.expressApp as unknown as NodeHandler;
  })());

export default async function handler(
  req: IncomingMessage,
  res: ServerResponse,
): Promise<void> {
  (await app())(req, res);
}
`;
}
