// Copyright Ninemind.ai 2026. All Rights Reserved.
// This file is licensed under the MIT License.
// License text available at https://opensource.org/license/mit/

import {existsSync, mkdirSync, readFileSync, writeFileSync} from 'node:fs';
import path from 'node:path';
import {AgentError, ErrorCodes} from '@agentback/openapi';
import type {DeployArgs} from './args.js';
import type {Exec} from './exec.js';
import {resolveBuilder, enforceConsoleGate} from './detect.js';
import {generateEntry} from './generate-entry.js';
import {mergeVercelConfig} from './merge-config.js';
import {verifyDeploy, type VerifyResult} from './verify.js';

export interface RunDeps {
  exec: Exec;
  fetchFn: typeof fetch;
  cwd: string;
}
export interface RunOutcome {
  status: 'deployed' | 'ejected' | 'dry-run';
  url?: string;
  verify?: VerifyResult;
}

function detectPackageManager(): 'pnpm' | 'yarn' | 'bun' | 'npm' {
  const ua = process.env.npm_config_user_agent ?? '';
  if (ua.startsWith('pnpm')) return 'pnpm';
  if (ua.startsWith('yarn')) return 'yarn';
  if (ua.startsWith('bun')) return 'bun';
  return 'npm';
}

function writeRootFiles(
  args: DeployArgs,
  builder: {entry: string; exportName: string},
  includeConsoleAssets: boolean,
  cwd: string,
): void {
  // The builder entry is repo-root-relative; api/index.ts sits one level deeper
  // in api/, so a root-relative path (bare or ./-prefixed) gets a ../ prefix.
  // An absolute path passes through unchanged.
  const stripped = builder.entry.replace(/^\.\//, '');
  const entryFromApi = stripped.startsWith('/') ? stripped : '../' + stripped;
  const apiDir = path.join(cwd, 'api');
  const apiFile = path.join(apiDir, 'index.ts');
  if (existsSync(apiFile) && !args.force) {
    const current = readFileSync(apiFile, 'utf8');
    if (!current.includes('Generated by `agentback deploy vercel`')) {
      throw new AgentError(
        `api/index.ts already exists and was not generated by agentback. ` +
          `Re-run with --force to overwrite.`,
        {code: ErrorCodes.INVALID_INPUT},
      );
    }
  }
  mkdirSync(apiDir, {recursive: true});
  writeFileSync(
    apiFile,
    generateEntry({entry: entryFromApi, exportName: builder.exportName}),
  );

  const vercelPath = path.join(cwd, 'vercel.json');
  const existing = existsSync(vercelPath)
    ? (JSON.parse(readFileSync(vercelPath, 'utf8')) as Record<string, unknown>)
    : undefined;
  const {json, warnings} = mergeVercelConfig(existing, {
    packageManager: detectPackageManager(),
    includeConsoleAssets,
    force: args.force,
    eject: args.eject,
  });
  for (const w of warnings) console.warn(`warning: ${w}`);
  writeFileSync(vercelPath, JSON.stringify(json, null, 2) + '\n');
}

async function preflight(exec: Exec): Promise<void> {
  const who = await exec('vercel', ['whoami']);
  if (who.code !== 0) {
    throw new AgentError(
      'Vercel CLI is not installed or not authenticated. Install with ' +
        '`npm i -g vercel`, then run `vercel login` (and `vercel link`).',
      {code: ErrorCodes.INVALID_INPUT},
    );
  }
}

function parseUrl(stdout: string): string {
  const m = stdout.match(/https:\/\/\S+\.vercel\.app/);
  if (!m) {
    throw new AgentError('Could not find a deployment URL in vercel output.', {
      code: ErrorCodes.INVALID_INPUT,
    });
  }
  return m[0];
}

export async function runVercelDeploy(
  args: DeployArgs,
  deps: RunDeps,
): Promise<RunOutcome> {
  const builder = resolveBuilder({
    entry: args.entry,
    exportName: args.exportName,
    cwd: deps.cwd,
  });
  const isConsoleBuilder = builder.exportName === 'buildConsoleApp';
  const consoleIntent = args.console || isConsoleBuilder;
  enforceConsoleGate({console: consoleIntent, unsafePublicConsole: args.unsafePublicConsole});
  if (args.console && !isConsoleBuilder) {
    console.warn(
      'warning: --console was set but the resolved builder is not the console builder; no console assets bundled.',
    );
  }
  writeRootFiles(args, builder, isConsoleBuilder, deps.cwd);
  if (args.eject) return {status: 'ejected'};

  await preflight(deps.exec);
  if (args.dryRun) return {status: 'dry-run'};

  const deployArgs = [
    'deploy',
    ...(args.prod ? ['--prod'] : []),
    ...(args.yes ? ['--yes'] : []),
  ];
  const res = await deps.exec('vercel', deployArgs);
  if (res.code !== 0) {
    throw new AgentError(`vercel deploy failed (exit ${res.code}).`, {
      code: ErrorCodes.INVALID_INPUT,
    });
  }
  const url = parseUrl(res.stdout);
  const verify = await verifyDeploy(
    url,
    {verifyPath: args.verifyPath},
    deps.fetchFn,
  );
  return {status: 'deployed', url, verify};
}
