// Copyright Ninemind.ai 2026. All Rights Reserved.
// This file is licensed under the MIT License.
// License text available at https://opensource.org/license/mit/

import {existsSync, mkdirSync, readFileSync, writeFileSync} from 'node:fs';
import path from 'node:path';
import {AgentError, ErrorCodes} from '@agentback/openapi';
import type {DeployArgs} from './args.js';
import {resolveBuilder, enforceConsoleGate} from './detect.js';
import {verifyDeploy} from './verify.js';
import type {DeployTarget, RunDeps, RunOutcome, GenerateOpts} from './deploy-target.js';

function writeEdit(cwd: string, edit: {path: string; contents: string}, force: boolean): void {
  const abs = path.join(cwd, edit.path);
  // Clobber guard only for the generated entry, mirroring Phase 1.
  if (existsSync(abs) && !force) {
    const cur = readFileSync(abs, 'utf8');
    if (!cur.includes('Generated by `agentback deploy`') &&
        !cur.includes('Generated by `agentback deploy vercel`')) {
      // Config files (vercel.json/wrangler.toml) are merged upstream, so an
      // existing one is expected; only guard generated *source* entries.
      if (edit.path.endsWith('.ts') || edit.path.endsWith('.js')) {
        throw new AgentError(
          `${edit.path} already exists and was not generated by agentback. ` +
            `Re-run with --force to overwrite.`,
          {code: ErrorCodes.INVALID_INPUT},
        );
      }
    }
  }
  mkdirSync(path.dirname(abs), {recursive: true});
  writeFileSync(abs, edit.contents);
}

export async function runDeploy(
  args: DeployArgs,
  target: DeployTarget,
  deps: RunDeps,
): Promise<RunOutcome> {
  const builder = resolveBuilder({entry: args.entry, exportName: args.exportName, cwd: deps.cwd});
  const isConsoleBuilder = builder.exportName === 'buildConsoleApp';
  const consoleIntent = args.console || isConsoleBuilder;
  enforceConsoleGate({console: consoleIntent, unsafePublicConsole: args.unsafePublicConsole});
  if (args.console && !isConsoleBuilder) {
    console.warn(
      'warning: --console was set but the resolved builder is not the console builder; no console assets bundled.',
    );
  }

  const opts: GenerateOpts = {builder, cwd: deps.cwd, isConsoleBuilder, force: args.force, eject: args.eject};
  writeEdit(deps.cwd, target.generateEntry(opts), args.force);
  for (const edit of target.generateConfig(opts)) writeEdit(deps.cwd, edit, true);

  if (args.eject) return {status: 'ejected'};

  const diags = await target.preflight(opts, deps);
  const bad = diags.find(d => !d.ok);
  if (bad) throw new AgentError(bad.message, {code: ErrorCodes.INVALID_INPUT});
  if (args.dryRun) return {status: 'dry-run'};

  const {url} = await target.deploy(args, deps);
  const verify = await verifyDeploy(url, {verifyPath: args.verifyPath || target.defaultVerifyPath()}, deps.fetchFn);
  return {status: 'deployed', url, verify};
}
