// Copyright ninemind.ai 2026. All Rights Reserved.
// This file is licensed under the MIT License.
// License text available at https://opensource.org/license/mit/

import {generateIdSync} from '@agentback/common';

/**
 * Generate a (globally) unique identifier in a very fast way.
 * The format may change in the future; today it is a short alphanumeric id.
 *
 * Delegates to `@agentback/common`'s `generateIdSync` (nanoid-backed) — the
 * codebase's existing ID utility (also used by `@agentback/metering`), so we
 * reuse one mechanism rather than introducing another. nanoid generates
 * randomness only on call (never at module load), so importing this module —
 * and thus the whole DI container — is side-effect-free and edge-safe. Edge
 * runtimes (Cloudflare Workers) forbid "generating random values" in the global
 * scope; there is no construction step here to trip that (unlike `hyperid`,
 * which seeded a UUID eagerly at import).
 *
 * @internal
 */
export function generateUniqueId(): string {
  return generateIdSync();
}

/**
 * A regular expression for testing values generated by generateUniqueId.
 * `generateIdSync` uses an alphanumeric alphabet; the class is kept permissive
 * (incl. url-safe `-_`) to tolerate any future id-format change.
 * @internal
 */
export const UNIQUE_ID_PATTERN = /[A-Za-z0-9_-]+/;
